# Use root/example as user/password credentials
#removed container_name for users-mysql as we can not scale
#also need to remove port for scalling up
version: '2.2'

services:

  users-mysql:
    image: users-mysql
    depends_on:
        mysql-container:
            condition: service_healthy
    ports:
      - 8086
    scale: 3  

  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
    healthcheck:
        test: "/usr/bin/mysql --user=sa --password=password --execute \"SHOW DATABASES;\""
        timeout: 20s
        retries: 5
        
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    links:
        - mysql-container
    environment:
        PMA_HOST: mysql-container
        PMA_PORT: 3306
    ports:
        - '8087:80'